task {
  name: "Object detection"
  dataset {
    name: "Coco 2017"
    type: COCO
    path: "/sdcard/mlperf_datasets/coco/img/"
    groundtruth_src: "@assets/coco_val.pbtxt"
  }
  model {
    name: "SSD-MobileNets-v2 UInt8"
    src: "https://github.com/mlperf/mobile_app/raw/model_repo_v0.7/tflite/ssd_mobilenet_v2_300_uint8.tflite"
    offset: 1
    tags: "uint8"
  }
  model {
    name: "SSD-MobileNets-v2 F32"
    src: "https://github.com/mlperf/mobile_app/raw/model_repo_v0.7/tflite/ssd_mobilenet_v2_300_float.tflite"
    offset: 1
    tags: "float32"
  }
  min_query_count: 100
  min_duration_ms: 1000
}
