name: Checking pull request
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Checking pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Store Cloud storage key
        env:
          CLOUD_STORAGE_KEY: ${{ secrets.CLOUD_STORAGE_KEY }}
        run: echo $CLOUD_STORAGE_KEY > ~/work/_temp/_github_workflow/storage_key.json

      - name: Build all
        uses: docker://thaink/android-bazel:latest
        with:
          args: >
            build --remote_http_cache=https://storage.googleapis.com/mlperf_mobile_app_bazel_build_cache
            --google_credentials=/github/workflow/storage_key.json
            -c opt --cxxopt="--std=c++17" //...

      - name: Run unit tests
        uses: docker://thaink/android-bazel:latest
        with:
          args: >
            test --test_output=streamed
            --remote_http_cache=https://storage.googleapis.com/mlperf_mobile_app_bazel_unit_tests_cache
            --google_credentials=/github/workflow/storage_key.json
            -c opt --cxxopt="--std=c++17" //cpp/...
